#include <iostream>
using namespace std;

main(){
float number_1;
float number_2;
float number_3;
float number_4;
float number_5;
float number_6;
float number_7;
float number_8;
float number_9;
float number_10;
float number_11;
float number_12;
float number_13;
float number_14;
float number_15;
float total;
cout<< "Enter your 1st number  ";
cin>>number_1;
cout<< "Enter your 2st number  ";
cin>>number_2;
cout<< "Enter your 3st number  ";
cin>>number_3;
cout<< "Enter your 4st number  ";
cin>>number_4;
cout<< "Enter your 5st number  ";
cin>>number_5;
cout<< "Enter your 5st number  ";
cin>>number_5;
cout<< "Enter your 6st number  ";
cin>>number_6;
cout<< "Enter your 7st number  ";
cin>>number_7;
cout<< "Enter your 8st number  ";
cin>>number_8;
cout<< "Enter your 9st number  ";
cin>>number_9;
cout<< "Enter your 10st number  ";
cin>>number_10;
cout<< "Enter your 11st number  ";
cin>>number_11;
cout<< "Enter your 12st number  ";
cin>>number_12;
cout<< "Enter your 13st number  ";
cin>>number_13;
cout<< "Enter your 14st number  ";
cin>>number_14;
cout<< "Enter your 15st number  ";
cin>>number_15;
float adds;
float mul;
float subt;
float addds;
adds = number_1+number_2+number_3+number_4+number_5;
mul = number_6*number_7*number_8*number_9*number_10;
subt = (number_11) - (number_12) - (number_13) - (number_14) - (number_15);
addds = adds + mul;
total = addds+subt;
cout<< "Your total result is "<<total;
}